version: '3.7'
services:
    php8-sf6:
        container_name: php8-sf6
        build: php8-sf6
        ports:
            - "9900:8000"
        volumes:
            - ./project:/var/www/html
        networks:
            - npm-nw

   

 ftp:
    build:
      dockerfile: Dockerfile
      context: ftp/
    volumes:
      - "./html/users/:/ftp/"
      - "./ftp/users/:/ftp_users/"
      - "./ftp/default_data/:/default_data/"
    restart: unless-stopped
    network_mode: "host"
    env_file:
      - environment.yml

  mariadb:
    image: linuxserver/mariadb:latest
    restart: unless-stopped
    env_file:
      - environment.yml
    ports:
      - 3306:3306
    volumes:
      - ./mariadb/:/config
   

volumes:
    db-data:
        driver: local

    mariadb:
        driver: local
networks:

    npm-nw:
        external: true
