version: '3.7'
services:
    php8-sf6:
        container_name: php8-sf6
        build: php8-sf6
        ports:
            - "9900:8000"
        volumes:
            - ./project:/var/www/html
        networks:
            - npm-nw

   

    

    mysql:

        image: mysql:8.0

        environment:
            MYSQL_USER: admin
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_DATABASE: symfony6

        ports:

            - 6603:3306

        volumes:

            - mysql:/var/lib/mysql:rw
        networks:
            - npm-nw

   

volumes:
    db-data:
        driver: local

    mysql:
        driver: local
networks:

    npm-nw:
        external: true
